/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.3.1/userguide/building_java_projects.html in the Gradle documentation.
 */

group = "io.github.bfur64"
version = "0.9.0-SNAPSHOT-2"

tasks.processResources {
    val versionString = project.version.toString()

    inputs.property("version", versionString)

    filesMatching("io/github/bfur64/menu/settings.json.template") {
        expand(mapOf("version" to versionString))
    }

    rename("(.+)\\.template", "$1")
}

plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java-library`

    id("application")

    id("com.gradleup.shadow") version "9.3.1"

    id("com.vanniktech.maven.publish") version "0.36.0"
}

shadow {
    addShadowVariantIntoJavaComponent = false
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenLocal()
    mavenCentral()
}

dependencies {
    // Use JUnit test framework.
    testImplementation(libs.junit)

    // This dependency is exported to consumers, that is to say found on their compile classpath.
    api(libs.commons.math3)

    // This dependency is used internally, and not exposed to consumers on their own compile classpath.
    implementation(libs.guava)

    // Rendering Pipeline
    implementation("io.github.bfur64:tetrue-terminal:2.4.2")

    // JSON Reader
    implementation("tools.jackson.core:jackson-databind:3.1.3")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    mainClass ="examples.DemoEditable"
}

mavenPublishing {
    publishToMavenCentral()
    signAllPublications()

    coordinates(group.toString(), "menu-manager", version.toString())

    pom {
        name.set("menu-manager")
        description.set("A composable main menu system, built in Java using the Lanterna UI Library")
        inceptionYear.set("2026")
        url.set("https://github.com/BFUR64/menu-manager/")
        licenses {
            license {
                name.set("MIT License")
                url.set("https://opensource.org/license/mit")
                distribution.set("repo")
            }
        }
        developers {
            developer {
                id.set("BFUR64")
                name.set("Terrance")
                url.set("https://github.com/BFUR64/")
            }
        }
        scm {
            url.set("https://github.com/BFUR64/menu-manager/")
            connection.set("scm:git:https://github.com/BFUR64/menu-manager.git")
            developerConnection.set("scm:git:ssh://git@github.com/BFUR64/menu-manager.git")
        }
    }
}